import { auth } from '@/auth';
import ClientProviders from '@/providers';
import '@worldcoin/mini-apps-ui-kit-react/styles.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Template Mini App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientProviders session={session}>
        <header className="p-4 bg-black text-white text-center">
          <h1 className="text-xl font-bold">wKingw</h1>
        </header>
        <main className="p-4">{children}</main>
        <footer className="p-4 text-center text-sm text-gray-500">© 2025 - Powered by SAPE</footer>
        </ClientProviders>
      </body>

    </html>
  );
}
